### PR TITLE
fix case-sensitive files

### PR DESCRIPTION
**Pull request by Shanjaq**

### CODE REVIEW

**Review by sezero — COMMENTED** [review]
MG_AI.hc has always been uppercase in the filename part in all hexen2 projects: I suggest that you keep it as is,

**Comment by sezero** [comment]
Should be good I guess. (Close #5 too.)

**Comment by sezero** [comment]
BTW, the progs.dat binary is outdated.

**Comment by Shanjaq** [comment]
ah yes, the progs.dat gets uploaded separately to the Releases when there's enough changed.  thanks for resolving these compilation issues :)

**Pull request merged**
